os: linux
language: generic
cache:
    directories:
      - $HOME/.cache/pip
      - .hypothesis
      
git:
    depth: false

jobs:
    fast_finish: true
    include:

        # test installing bottleneck tarball before installing numpy;
        # start this test first because it takes the longest

         # doc check
               
        - os: linux
          arch: arm64
          env: TEST_DEPS="sphinx numpydoc gitpython"
               PYTHON_VERSION="3.7"
               PYTHON_ARCH="64"
               TEST_RUN="doc"

        # coverage
        - os: linux
          arch: arm64
          env: TEST_DEPS="numpy pytest hypothesis"
               PYTHON_VERSION="3.6"
               PYTHON_ARCH="64"

         # python 3.7
               
        - os: linux
          arch: arm64
          dist: bionic
          env: TEST_DEPS="numpy pytest hypothesis"
               PYTHON_VERSION="3.7"
               PYTHON_ARCH="64"

         # python 3.8 conda numpy
               
        - os: linux
          arch: arm64
          env: TEST_DEPS="numpy pytest hypothesis"
               PYTHON_VERSION="3.8"
               PYTHON_ARCH="64"

         # python 3.8 conda numpy + sdist
               
        - os: linux
          arch: arm64
          env: TEST_DEPS="numpy pytest hypothesis"
               PYTHON_VERSION="3.8"
               PYTHON_ARCH="64"
               TEST_RUN="sdist"

before_install:
    - uname -a
    - source "tools/travis/conda_setup.sh"

install:
    - source "tools/travis/conda_install.sh"

script:

    - source "tools/travis/bn_setup.sh"

notifications:
    email:
        on_success: never
        on_failure: always
