[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy>=1.16.6; python_version>='3.7' and platform_system=='AIX'",
    "numpy>=1.16.6; python_version>='3.7' and platform_system!='AIX'",
]
