[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy==1.18.0; python_version>='3.7' and platform_system=='AIX'",
    "numpy==1.18.0; python_version>='3.7' and platform_system!='AIX'",
]
